version: "3.7"

services:
  web:
    build: ./services/web
    ports:
      - 5000:5000
    env_file:
      - ./.env.dev
    command: python3 ./manage.py run -h 0.0.0.0
    depends_on:
      - db
  db:
    image: postgres:12-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env.dev.db

volumes:
  postgres_data:
